### ISSUE TITLE
How to install empiricalGameTheory packages?

### ISSUE THREAD

**Issue by wbk123** [phelps-sg/r-heuristic-games#1]
How to install empiricalGameTheory package?My R version is 3.5.0, system is Windows 7.

**Comment by phelps-sg** [comment]
As per the [readme](https://github.com/phelps-sg/r-heuristic-games/blob/master/readme.md), execute the following command in the shell (in Windows, the operating system shell is called the "Windows Command Prompt").

~~~bash
R CMD INSTALL empiricalGameTheory
~~~

If this does not work, please post more details of any problems you are encountering, and copy and paste exact error messages.  Also, for more help installing packages, please consult the standard [r-project documentation](https://cran.r-project.org/doc/manuals/R-admin.html#Installing-packages), which provides instructions for different operating systems.
